-- Workout library and weekly plans (US-010).

-- What a set records. Stored as an array of these rather than four booleans, so the set-logging UI
-- in US-011 can be generated by iterating the array in a fixed order.
create type public.tracked_field as enum ('reps', 'weight', 'duration', 'distance');

create table public.workouts (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 60),
  group_name text check (group_name is null or char_length(group_name) between 1 and 40),
  tracks public.tracked_field[] not null check (cardinality(tracks) between 1 and 4),
  default_sets int not null default 3 check (default_sets between 1 and 10),
  notes text check (notes is null or char_length(notes) between 1 and 200),
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Case-insensitive uniqueness, enforced here rather than by a query-then-insert in the action,
-- which races with itself.
create unique index workouts_owner_name on public.workouts (owner_id, lower(name));

create table public.plans (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 60),
  is_active boolean not null default false,
  notes text check (notes is null or char_length(notes) between 1 and 200),
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- At most one active plan per owner. A partial unique index, so two concurrent activations cannot
-- both succeed -- application code cannot promise that.
create unique index plans_single_active on public.plans (owner_id) where is_active;

create table public.plan_days (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  plan_id uuid not null references public.plans(id) on delete cascade,
  -- 0 = Monday … 6 = Sunday. ISO order, so the week strip renders in the order it is stored.
  weekday int not null check (weekday between 0 and 6),
  name text check (name is null or char_length(name) between 1 and 60),
  is_rest boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (plan_id, weekday)
);

create table public.plan_items (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  plan_day_id uuid not null references public.plan_days(id) on delete cascade,
  workout_id uuid not null references public.workouts(id) on delete cascade,
  position int not null,
  target_sets int check (target_sets is null or target_sets between 1 and 20),
  target_reps int check (target_reps is null or target_reps between 1 and 100),
  target_weight numeric(6, 2) check (target_weight is null or target_weight >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- An exercise appears at most once per day.
  unique (plan_day_id, workout_id)
);

create index plan_days_plan on public.plan_days (plan_id, weekday);
create index plan_items_day on public.plan_items (plan_day_id, position);

/*
 * Creating a plan must also create its seven rest days, or the editor has to invent them and every
 * read has to cope with a plan that has fewer than seven. One function, called by the seed below
 * and by the Server Action, keeps that atomic.
 */
create or replace function public.create_plan(plan_name text, activate boolean default false)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  new_id uuid;
begin
  if activate then
    update public.plans set is_active = false where owner_id = (select auth.uid()) and is_active;
  end if;

  insert into public.plans (name, is_active) values (plan_name, activate) returning id into new_id;

  insert into public.plan_days (plan_id, weekday, is_rest)
  select new_id, generate_series(0, 6), true;

  return new_id;
end;
$$;

/*
 * Activating is two statements that must not be seen apart, or the partial unique index rejects
 * the second and leaves nothing active.
 */
create or replace function public.activate_plan(target uuid)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  update public.plans set is_active = false where owner_id = (select auth.uid()) and is_active;
  update public.plans set is_active = true where id = target and owner_id = (select auth.uid());
end;
$$;

create trigger workouts_set_updated_at before update on public.workouts
  for each row execute function private.set_updated_at();
create trigger plans_set_updated_at before update on public.plans
  for each row execute function private.set_updated_at();
create trigger plan_days_set_updated_at before update on public.plan_days
  for each row execute function private.set_updated_at();
create trigger plan_items_set_updated_at before update on public.plan_items
  for each row execute function private.set_updated_at();

alter table public.workouts enable row level security;
alter table public.plans enable row level security;
alter table public.plan_days enable row level security;
alter table public.plan_items enable row level security;

create policy "owner can do everything" on public.workouts for all to authenticated
  using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy "require aal2" on public.workouts as restrictive for all to authenticated
  using ((select auth.jwt() ->> 'aal') = 'aal2') with check ((select auth.jwt() ->> 'aal') = 'aal2');

create policy "owner can do everything" on public.plans for all to authenticated
  using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy "require aal2" on public.plans as restrictive for all to authenticated
  using ((select auth.jwt() ->> 'aal') = 'aal2') with check ((select auth.jwt() ->> 'aal') = 'aal2');

create policy "owner can do everything" on public.plan_days for all to authenticated
  using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy "require aal2" on public.plan_days as restrictive for all to authenticated
  using ((select auth.jwt() ->> 'aal') = 'aal2') with check ((select auth.jwt() ->> 'aal') = 'aal2');

create policy "owner can do everything" on public.plan_items for all to authenticated
  using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy "require aal2" on public.plan_items as restrictive for all to authenticated
  using ((select auth.jwt() ->> 'aal') = 'aal2') with check ((select auth.jwt() ->> 'aal') = 'aal2');

/*
 * Starter library and an empty week (US-010 §6).
 *
 * A function the app calls, not INSERTs in this migration: every row here is owner-scoped via
 * `auth.uid()`, and a migration runs with no auth context, so a plain INSERT would write rows
 * owned by nobody — invisible under RLS and impossible to delete from the app.
 *
 * Idempotent by construction: it does nothing once the owner has any workout, so calling it on
 * every visit to the gym screens is safe.
 */
create or replace function public.seed_gym_defaults()
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  uid uuid := (select auth.uid());
begin
  if uid is null then return; end if;
  if exists (select 1 from public.workouts where owner_id = uid) then return; end if;

  insert into public.workouts (name, group_name, tracks, default_sets) values
    ('Squat',                  'Legs',      array['reps','weight']::public.tracked_field[], 3),
    ('Deadlift',               'Legs',      array['reps','weight']::public.tracked_field[], 3),
    ('Romanian Deadlift',      'Legs',      array['reps','weight']::public.tracked_field[], 3),
    ('Leg Press',              'Legs',      array['reps','weight']::public.tracked_field[], 3),
    ('Bench Press',            'Chest',     array['reps','weight']::public.tracked_field[], 3),
    ('Incline Dumbbell Press', 'Chest',     array['reps','weight']::public.tracked_field[], 3),
    ('Overhead Press',         'Shoulders', array['reps','weight']::public.tracked_field[], 3),
    ('Lateral Raise',          'Shoulders', array['reps','weight']::public.tracked_field[], 3),
    ('Barbell Row',            'Back',      array['reps','weight']::public.tracked_field[], 3),
    ('Lat Pulldown',           'Back',      array['reps','weight']::public.tracked_field[], 3),
    ('Pull-up',                'Back',      array['reps']::public.tracked_field[],          3),
    ('Dumbbell Curl',          'Arms',      array['reps','weight']::public.tracked_field[], 3),
    ('Triceps Pushdown',       'Arms',      array['reps','weight']::public.tracked_field[], 3),
    ('Plank',                  'Core',      array['duration']::public.tracked_field[],      3);

  -- Only seed a plan if there is none at all, so this never adds a second "My week".
  if not exists (select 1 from public.plans where owner_id = uid) then
    perform public.create_plan('My week', true);
  end if;
end;
$$;
